In [71]:
import torch
import torch.nn.functional as F
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from torch import nn


In [72]:
class W2VNeuralNetork(nn.Module):
    def __init__(self, vocab_size= 5, embeddings_dim = 8):
        super().__init__()
        self.fc1 = nn.Linear(vocab_size, embeddings_dim, bias=False)
        self.out = nn.Linear(embeddings_dim, vocab_size, bias=False)

    def forward(self, x):
        x = self.fc1(x)
        x = self.out(x)
        return x


In [73]:
def tokenize(text: str) -> str:
    tokens = np.array(text.lower().split()).reshape(-1,1)
    return tokens

In [74]:
def encoding(tokens: np.array):
    enc = OneHotEncoder(sparse_output=False)
    return enc.fit_transform(tokens)

In [75]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [76]:
phrase = encoding(tokenize("oi eu sou o thalles"))
print(phrase)

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
